# Generated by Django 2.2.4 on 2019-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate', models.CharField(max_length=8)),
                ('car_make', models.CharField(max_length=30)),
                ('year_of_make', models.IntegerField()),
                ('car_price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('availablility', models.CharField(max_length=10)),
            ],
        ),
    ]
