# Generated by Django 2.2.4 on 2019-09-05 05:25

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carplate', models.CharField(max_length=8)),
                ('car_make', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Volvo', 'Volvo')], default='Audi', max_length=15)),
                ('car_model', models.CharField(max_length=30)),
                ('car_type', models.CharField(choices=[('Luxury Sedan', 'Luxury Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('MPV', 'MPV'), ('Sports', 'Sports'), ('Stationwagon', 'Stationwagon'), ('Hybrid', 'Hybrid')], default='Luxury Sedan', max_length=15)),
                ('year_of_make', models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019')], default='2009')),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('image', pyuploadcare.dj.models.ImageField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
