# Generated by Django 2.2.4 on 2019-09-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carplate', models.CharField(max_length=8)),
                ('car_make', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Jaguar', 'Jaguar'), ('Volvo', 'Volvo')], default='Audi', max_length=2)),
                ('car_model', models.CharField(max_length=30)),
                ('car_type', models.CharField(choices=[('Luxury Sedan', 'Luxury Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('MPV', 'MPV'), ('Sports', 'Sports'), ('Stationwagon', 'Stationwagon'), ('Hybrid', 'Hybrid')], default='Luxury Sedan', max_length=2)),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('description', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CarDetail',
        ),
    ]
