# Generated by Django 2.2.4 on 2019-09-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0002_auto_20190904_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carplate', models.CharField(max_length=8)),
                ('car_make', models.CharField(choices=[('AUD', 'Audi'), ('BMW', 'BMW'), ('MER', 'Mercedes-Benz'), ('VOL', 'Volvo')], default='AUD', max_length=2)),
                ('car_model', models.CharField(max_length=30)),
                ('car_type', models.CharField(choices=[('LUXSEDAN', 'Luxury Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV'), ('MPV', 'MPV'), ('SPORT', 'Sports'), ('SWAGON', 'Stationwagon'), ('HYBRID', 'Hybrid')], default='LUXSEDAN', max_length=2)),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('availability', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CarDetails',
        ),
    ]
