# Generated by Django 2.2.4 on 2019-09-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0003_auto_20190904_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_make',
            field=models.CharField(choices=[('AUD', 'Audi'), ('BMW', 'BMW'), ('MER', 'Mercedes-Benz'), ('VOL', 'Volvo')], default='AUD', max_length=3),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_type',
            field=models.CharField(choices=[('LUXSEDAN', 'Luxury Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV'), ('MPV', 'MPV'), ('SPORT', 'Sports'), ('SWAGON', 'Stationwagon'), ('HYBRID', 'Hybrid')], default='LUXSEDAN', max_length=10),
        ),
    ]
