# Generated by Django 2.2.4 on 2019-09-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0006_auto_20190904_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='availability',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(choices=[('available', True), ('sold', False)], default=True),
        ),
    ]
