# Generated by Django 2.2.4 on 2019-09-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0007_auto_20190904_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(choices=[(True, 'Available'), (False, 'Sold')], default=True),
        ),
    ]
