# Generated by Django 2.2.4 on 2019-09-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0009_auto_20190904_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='carplate',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
