# Generated by Django 2.2.4 on 2019-09-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0010_auto_20190904_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_make',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Volvo', 'Volvo')], default='Audi', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_type',
            field=models.CharField(choices=[('Luxury Sedan', 'Luxury Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('MPV', 'MPV'), ('Sports', 'Sports'), ('Stationwagon', 'Stationwagon'), ('Hybrid', 'Hybrid')], default='Luxury Sedan', max_length=15),
        ),
    ]
