# Generated by Django 2.2.4 on 2019-09-05 03:11

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0013_auto_20190904_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
